language: php

sudo: false

matrix:
  include:
  - php: '7.2'
  - php: '7.3'
  - php: '7.4'
  - php: '8.0'

cache:
  directories:
  - "$HOME/.composer/cache"

before_install:
- travis_retry composer self-update
- travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
- composer test:ci

